### PR TITLE
Class, module and package reorganization

### PR DESCRIPTION
**Pull request by pkohvaei**

### CODE REVIEW

**Comment by pkohvaei** [comment]
Next step is the documentation and style check.

**Comment by fabriziocosta** [comment]
..nop, cannot merge the pull request. you have to resolve the conflicts on your end before submitting it again.

**Comment by pkohvaei** [comment]
Could you please send those git commands you showed?

**Comment by fabriziocosta** [comment]
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b pkohvaei-master master
git pull https://github.com/pkohvaei/RNAsynth.git master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff pkohvaei-master
git push origin master

**Comment by pkohvaei** [comment]
-bash-4.2$ git checkout -b pkohvaei-master master
Switched to a new branch 'pkohvaei-master'
-bash-4.2$ git branch
  dev
  master
- pkohvaei-master
  -bash-4.2$ git pull https://github.com/pkohvaei/RNAsynth.git master
  From https://github.com/pkohvaei/RNAsynth
  - branch            master     -> FETCH_HEAD
    Already up-to-date.
    -bash-4.2$ git checkout master
    Switched to branch 'master'
    Your branch is up-to-date with 'origin/master'.
    -bash-4.2$ git merge --no-ff pkohvaei-master
    Already up-to-date.
    -bash-4.2$ git push origin master
    Everything up-to-date

**Pull request merged**
